In [1]:
import pandas as pd
import os.path

In [2]:
hchn = pd.read_excel (os.path.abspath ("../inputs/HCHN ICD-10 Diagnoses.xlsx"), sheet_name = "HCHN Diagnoses")

In [3]:
pd.options.display.max_columns = 80
pd.options.display.max_rows = 50
lista_hchn = hchn.Dx.unique()
lista_hchn

array(['C25.0', 'C25.1', 'C25.2', ..., 'R33.9', 'R39.14', 'R80.2'],
      dtype=object)

In [ ]:
assertus_report = pd.read_excel (os.path.abspath ("../inputs/ReportesAssertus/assertus_report_sept2019tojuly212020.xlsx"), sheet_name = "GenericReport-CSV-(072120)") 
assertus_report = assertus_report[assertus_report["InsName"] != "APS HEALTHCARE PUERTO RICO INC"] 
#assertus_report = assertus_report [[ "sCardContractNo", "dDateFrom", "Dx1", "Dx2", "Dx3", "Dx4", "Dx5", "Dx6", "Dx7", "Dx8", "Dx9", "Dx10", "Dx11", "Dx12","sProcedureCode", "sInsuranceNo"]]
#assertus_report.head()
assertus_report

In [31]:
assertus_report["is_HCHN"] = (assertus_report["Dx1"].isin(lista_hchn)) | (assertus_report["Dx2"].isin(lista_hchn)) | (assertus_report["Dx3"].isin(lista_hchn)) | (assertus_report["Dx4"].isin(lista_hchn)) | (assertus_report["Dx5"].isin(lista_hchn)) | (assertus_report["Dx6"].isin(lista_hchn)) | (assertus_report["Dx7"].isin(lista_hchn)) | (assertus_report["Dx8"].isin(lista_hchn)) | (assertus_report["Dx9"].isin(lista_hchn)) | (assertus_report["Dx10"].isin(lista_hchn)) | (assertus_report["Dx11"].isin(lista_hchn)) | (assertus_report["Dx12"].isin(lista_hchn))

In [32]:
#Traer la ultima fecha con encuentro HCHN
assertus_report = assertus_report[assertus_report["is_HCHN"]]
assertus_report["orden"] = assertus_report.groupby("sCardContractNo")["dDateFrom"].rank(method="dense", ascending=False).astype(int)
print (assertus_report)

       sCardContractNo           dDateFrom    Dx1     Dx2     Dx3      Dx4  \
251        80010340499 2020-01-23 08:12:00  E04.2  E88.81   E66.9    K76.0
257        80030110912 2020-01-16 08:13:18  E11.9     NaN     NaN      NaN
268        80000269989 2020-01-10 11:58:17  B34.9     I10  E66.01  M25.569
269        80000269989 2020-01-10 11:58:17  B34.9     I10  E66.01  M25.569
270        80000269989 2020-01-10 11:58:17  B34.9     I10  E66.01  M25.569
...                ...                 ...    ...     ...     ...      ...
104638     80016556646 2020-06-24 07:12:09  I11.9   I70.0   J32.8   N39.41
104639     80016556646 2020-06-24 07:12:09  I11.9   I70.0   J32.8   N39.41
104640     80016556646 2020-06-24 07:12:09  I11.9   I70.0   J32.8   N39.41
104641     80016556646 2020-06-24 07:12:09  I11.9   I70.0   J32.8   N39.41
104642     80016556646 2020-06-24 07:12:09  I11.9   I70.0   J32.8   N39.41

           Dx5     Dx6     Dx7  Dx8  Dx9 Dx10 Dx11 Dx12 sProcedureCode  \
251        I10     NaN     NaN  NaN  NaN  NaN  NaN  NaN          99213
257        NaN     NaN     NaN  NaN  NaN  NaN  NaN  NaN          99213
268     Z01.30  Z68.43     NaN  NaN  NaN  NaN  NaN  NaN          99213
269     Z01.30  Z68.43     NaN  NaN  NaN  NaN  NaN  NaN          3008F
270     Z01.30  Z68.43     NaN  NaN  NaN  NaN  NaN  NaN          3074F
...        ...     ...     ...  ...  ...  ...  ...  ...            ...
104638  G47.30   F41.9  Z68.35  NaN  NaN  NaN  NaN  NaN          3074F
104639  G47.30   F41.9  Z68.35  NaN  NaN  NaN  NaN  NaN          2010F
104640  G47.30   F41.9  Z68.35  NaN  NaN  NaN  NaN  NaN          1126F
104641  G47.30   F41.9  Z68.35  NaN  NaN  NaN  NaN  NaN          3078F
104642  G47.30   F41.9  Z68.35  NaN  NaN  NaN  NaN  NaN          3028F

         sInsuranceNo  is_HCHN  orden
251     FIRST MEDICAL     True      1
257     FIRST MEDICAL     True      8
268     FIRST MEDICAL     True      3
269     FIRST MEDICAL     True      3
270     FIRST MEDICAL     True      3
...               ...      ...    ...
104638      SSS VITAL     True      2
104639      SSS VITAL     True      2
104640      SSS VITAL     True      2
104641      SSS VITAL     True      2
104642      SSS VITAL     True      2

[56587 rows x 18 columns]

In [33]:
assertus_report = assertus_report[assertus_report["orden"] == 1]
assertus_report[assertus_report.columns[:2]][ assertus_report["sCardContractNo"] == 80000043528 ]

#Automatizando Cpts
assertus_report [assertus_report.sProcedureCode.isin([99441, 99442, 99443,99213, 99203])]
assertus_report = assertus_report [assertus_report.sProcedureCode.isin([99441, 99442, 99443,99213, 99203])]
assertus_report

,sCardContractNo,dDateFrom,Dx1,Dx2,Dx3,Dx4,Dx5,Dx6,Dx7,Dx8,Dx9,Dx10,Dx11,Dx12,sProcedureCode,sInsuranceNo,is_HCHN,orden
251,80010340499,2020-01-23 08:12:00,E04.2,E88.81,E66.9,K76.0,I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,FIRST MEDICAL,True,1
330,80006434303,2020-01-23 09:06:16,I11.9,Z00.00,J45.909,I73.9,E55.9,J30.9,E05.90,NaN,NaN,NaN,NaN,NaN,99213,FIRST MEDICAL,True,1
374,80005151428,2020-01-16 08:08:14,N40.0,E03.9,E78.00,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,FIRST MEDICAL,True,1
409,80007822670,2020-01-14 13:30:30,I11.9,E03.9,E79.0,Z76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,FIRST MEDICAL,True,1
555,80025505779,2019-12-19 07:07:26,J06.9,J45.998,L30.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,FIRST MEDICAL,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104597,80001841864,2020-06-19 07:12:09,M25.562,G80.9,J45.909,M19.072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,SSS VITAL,True,1
104603,80000165416,2020-06-22 07:12:09,I10,E78.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99442,SSS VITAL,True,1
104612,80008063213,2020-06-25 07:12:09,I10,Z76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99441,SSS VITAL,True,1
104617,80000020192,2020-06-17 10:26:48,I11.9,E78.2,E03.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99441,SSS VITAL,True,1
104629,80019620756,2020-06-24 07:12:09,I11.9,E78.2,J32.8,Z76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99441,SSS VITAL,True,1

In [35]:
assertus_report.to_excel("outputs\Reportes_Solo_HCHN\Reporte_Solo_HCHN_sept2019tojuly212020.xlsx", index=False)